# Generated by Django 4.2.5 on 2024-04-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepayment', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
