# Generated by Django 4.2.5 on 2024-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepayment', '0004_history_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orderid', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
